[env]
_.file = ".env"
SENTRY_DSN = "https://7fd4c058e6685608ada24d63281f6d59@o55858.ingest.us.sentry.io/4507279390539776"
SENTRY_ENVIRONMENT = "dev"
PORT = "3000"
URL = "http://localhost:3000"
DEV = "true"

DB_TYPE = "postgres"
DATABASE_URL = "postgresql://postgres:root@127.0.0.1:5432/postgres"
GOOSE_DRIVER = "postgres"
GOOSE_DBSTRING = "postgresql://postgres:root@127.0.0.1:5432/postgres"
GOOSE_MIGRATION_DIR = "./internal/db/migrations"

[tools]
go = "1.24"
staticcheck = "latest"

[tasks.build]
description = "Build the server binary"
depends = "buildjs"
env.CGO_ENABLED = "0"
run = ["go build -o no-time-to-explain cmd/server/main.go"]

[tasks.run]
description = "Execute the app in development mode"
depends = "buildjs"
run = ["docker compose up -d", "go run cmd/server/main.go"]

[tasks.buildjs]
description = "Build the WASM binary"
env.CGO_ENABLED = "0"
env.GOOS = "js"
env.GOARCH = "wasm"
run = ["go build -o internal/server/assets/app.wasm cmd/app/main.go"]

[tasks.seed]
description = "Populate the database with seeds"
env.GOOSE_MIGRATION_DIR = "./internal/db/seeds"
run = ["go tool goose --no-versioning up"]
